export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";

export const SHOWLOADER = "SHOWLOADER";
export const HIDELOADER = "HIDELOADER";

export const SETTOKEN = "SETTOKEN";
export const CLEARTOKEN = "CLEARTOKEN";

export const CAN_EDIT = "CAN_EDIT";
export const CANNOT_EDIT = "CANNOT_EDIT";

export const SET_REGISTER_DATA = "SETREGISTRATIONDATA";
export const CLEAR_REGISTER_DATA = "CLEARREGISTRATIONDATA";

// export const ITEMS_TO_DISPLAY = "ITEMS_TO_DISPLAY";
// export const SET_ITEMS_TO_DISPLAY = "SET_ITEMS_TO_DISPLAY";
// export const SET_ARCHIVE_FILTERED_ITEMS = "SET_ARCHIVE_FILTERED_ITEMS";
// export const SET_ARCHIVE_LOADING = "SET_ARCHIVE_LOADING";
